name: shasum hash

on:
  push:
    branches: [main]

permissions:
  pull-requests: write
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Build
      uses: seepine/hash-files@v1
      id: get-hash
      with: 
        patterns: '**/README.md'
        
    - name: Echo hash
      run: echo ${{ steps.get-hash.outputs.hash }}
        